"""DAGL CLI — Deploy serverless workflow orchestration to existing Lambda functions.

This is the new-architecture CLI that:
- Compiles workflow.dag → per-function configs
- Attaches the DAGL runtime Layer to existing Lambda functions
- Sets Handler, env vars, and IAM for direct-invocation orchestration
- Optionally creates API Gateway / EventBridge triggers

Usage:
    dagl compile                  # Parse workflow.dag, validate types
    dagl deploy                   # Attach Layer + config to functions
    dagl undeploy                 # Restore original function configs
    dagl invoke -f input.json     # Trigger the workflow
    dagl status                   # Show current orchestration state

Requires: dagl.yaml in the project directory with function mapping.
"""

import argparse
import json
import os
import sys
import time
import uuid
import zipfile
import tempfile
import io
from pathlib import Path
from urllib.request import urlopen

# Add parent directory for compiler imports
sys.path.insert(0, str(Path(__file__).parent.parent / "unum-cli"))


# ─── Configuration ───────────────────────────────────────────────────────────────

DEFAULT_LAYER_NAMES = {
    "python": "dagl-runtime-python",
    "nodejs": "dagl-runtime-nodejs",
}
DEFAULT_DS_NAME = "unum-intermediate-datastore"
DEFAULT_DS_TYPE = "dynamodb"

# Handler paths differ by runtime
DAGL_HANDLERS = {
    "python": "dagl_runtime.main.handler",
    "nodejs": "dagl_wrapper.handler",
}


def detect_runtime_family(runtime_str: str) -> str:
    """Detect 'python' or 'nodejs' from a Lambda runtime string like 'python3.13' or 'nodejs20.x'."""
    if runtime_str.startswith("python"):
        return "python"
    if runtime_str.startswith("nodejs"):
        return "nodejs"
    raise RuntimeError(f"Unsupported Lambda runtime: {runtime_str}. DAGL supports python and nodejs.")


def resolve_latest_layer_arn(layer_name: str, region: str) -> str:
    """Resolve a layer name to the latest published version ARN."""
    import boto3
    client = boto3.client("lambda", region_name=region)
    resp = client.list_layer_versions(LayerName=layer_name, MaxItems=1)
    versions = resp.get("LayerVersions", [])
    if not versions:
        raise RuntimeError(f"No versions found for layer '{layer_name}' in {region}")
    return versions[0]["LayerVersionArn"]


# Node.js wrapper content - injected into function code package
NODEJS_WRAPPER_JS = """\
// DAGL Runtime Wrapper - Auto-generated by 'dagl deploy'
// This file bridges the Lambda handler to the DAGL runtime Layer.
// require() resolves 'dagl_runtime/main' via NODE_PATH (/opt/nodejs/node_modules)
module.exports = require('dagl_runtime/main');
"""


def _inject_nodejs_wrapper(lambda_client, func_ref):
    """Download function code, inject dagl_wrapper.js, re-upload.
    
    Returns True on success. Lambda Node.js handler resolution only looks in
    /var/task (function code), not in Layer paths. So we inject a tiny wrapper
    that require()'s the Layer module.
    """
    # Get current code download URL
    resp = lambda_client.get_function(FunctionName=func_ref)
    code_url = resp["Code"]["Location"]
    
    # Download the zip
    with urlopen(code_url) as r:
        original_zip = r.read()
    
    # Add dagl_wrapper.js to the zip
    buf = io.BytesIO()
    with zipfile.ZipFile(io.BytesIO(original_zip), 'r') as zin:
        with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                if item.filename == 'dagl_wrapper.js':
                    continue  # Replace if exists
                zout.writestr(item, zin.read(item.filename))
            zout.writestr('dagl_wrapper.js', NODEJS_WRAPPER_JS)
    
    # Upload modified code
    buf.seek(0)
    lambda_client.update_function_code(
        FunctionName=func_ref,
        ZipFile=buf.read(),
    )
    
    # Wait for update to complete
    import botocore
    waiter = lambda_client.get_waiter('function_updated_v2')
    waiter.wait(FunctionName=func_ref, WaiterConfig={'Delay': 2, 'MaxAttempts': 30})
    
    return True


def _remove_nodejs_wrapper(lambda_client, func_ref):
    """Remove dagl_wrapper.js from function code package."""
    resp = lambda_client.get_function(FunctionName=func_ref)
    code_url = resp["Code"]["Location"]
    
    with urlopen(code_url) as r:
        original_zip = r.read()
    
    buf = io.BytesIO()
    removed = False
    with zipfile.ZipFile(io.BytesIO(original_zip), 'r') as zin:
        with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                if item.filename == 'dagl_wrapper.js':
                    removed = True
                    continue
                zout.writestr(item, zin.read(item.filename))
    
    if removed:
        buf.seek(0)
        lambda_client.update_function_code(
            FunctionName=func_ref,
            ZipFile=buf.read(),
        )
        waiter = lambda_client.get_waiter('function_updated_v2')
        waiter.wait(FunctionName=func_ref, WaiterConfig={'Delay': 2, 'MaxAttempts': 30})


# ─── Registry Helpers ────────────────────────────────────────────────────────────

def _get_registry(dagl_config):
    """Create a Registry from dagl.yaml 'registry' config. Returns None if not configured."""
    reg_cfg = dagl_config.get("registry")
    if not reg_cfg:
        return None
    try:
        from registry import Registry
        if "url" in reg_cfg:
            return Registry(url=reg_cfg["url"])
        return Registry(
            host=reg_cfg.get("host", "localhost"),
            port=reg_cfg.get("port", 6379),
            db=reg_cfg.get("db", 0),
            password=reg_cfg.get("password"),
        )
    except ImportError:
        print("\033[33mWarning:\033[0m redis package not installed. Run: pip install redis")
        return None
    except Exception as e:
        print(f"\033[33mWarning:\033[0m Cannot connect to registry: {e}")
        return None


def _get_account_id(region="eu-central-1"):
    """Get the current AWS account ID."""
    import boto3
    return boto3.client("sts", region_name=region).get_caller_identity()["Account"]


def load_dagl_config(path: str = "dagl.yaml") -> dict:
    """Load dagl.yaml project config."""
    import yaml
    
    if not os.path.exists(path):
        print(f"\033[31mError:\033[0m {path} not found.")
        print(f"Create one with 'dagl init' or manually:")
        print(f"""
platform: aws
region: eu-central-1

functions:
  FunctionName: lambda-function-name-or-arn
""")
        sys.exit(1)
    
    with open(path) as f:
        return yaml.safe_load(f)


def normalize_function_entry(func_value, default_platform="aws", default_region="eu-central-1"):
    """Normalize a function entry from dagl.yaml into a standard dict format.
    
    Accepts:
      - String: "my-function-name" → {"name": "my-function-name", "platform": "aws", "region": default}
      - Dict: {"name": "...", "platform": "gcp", ...} → passed through with defaults filled
    
    For GCP functions, auto-detects:
      - project: from gcloud config
      - region: defaults to "europe-west1"
      - runtime: inferred from source directory (requirements.txt → python312, package.json → nodejs20)
      - handler: defaults to "main.handler"
      - url: constructed from region + project + function name
    
    Returns dict with keys: name, platform, region, and optionally: project, url, arn, source, etc.
    """
    if isinstance(func_value, str):
        return {
            "name": func_value,
            "platform": default_platform,
            "region": default_region,
        }
    elif isinstance(func_value, dict):
        entry = dict(func_value)
        entry.setdefault("platform", default_platform)
        
        if entry["platform"] == "gcp":
            # GCP defaults
            entry.setdefault("region", "europe-west1")
            entry.setdefault("handler", "main.handler")
            
            # Auto-detect project from gcloud config if not specified
            if "project" not in entry:
                entry["project"] = _detect_gcp_project()
            
            # Auto-detect runtime from source directory
            if "runtime" not in entry and entry.get("source"):
                entry["runtime"] = _detect_gcp_runtime(entry["source"])
            entry.setdefault("runtime", "python312")
            
            # Auto-construct URL if not specified
            if "url" not in entry and entry.get("project"):
                region = entry["region"]
                project = entry["project"]
                name = entry.get("name", "")
                entry["url"] = f"https://{region}-{project}.cloudfunctions.net/{name}"
        else:
            entry.setdefault("region", default_region)
        
        if "name" not in entry:
            raise ValueError(f"Function entry must have a 'name' field: {func_value}")
        return entry
    else:
        raise ValueError(f"Invalid function entry (expected string or dict): {func_value}")


def _detect_gcp_project():
    """Auto-detect GCP project from gcloud config."""
    import subprocess
    try:
        gcloud_cmd = _find_gcloud()
        result = subprocess.run(
            [gcloud_cmd, "config", "get-value", "project"],
            capture_output=True, text=True, timeout=10
        )
        project = result.stdout.strip()
        if project and project != "(unset)":
            return project
    except Exception:
        pass
    return ""


def _detect_gcp_runtime(source_dir):
    """Infer GCP runtime from source directory contents."""
    if not os.path.isdir(source_dir):
        return "python312"
    if os.path.exists(os.path.join(source_dir, "requirements.txt")):
        return "python312"
    if os.path.exists(os.path.join(source_dir, "package.json")):
        return "nodejs20"
    # Check for .py or .js files
    for f in os.listdir(source_dir):
        if f.endswith(".py"):
            return "python312"
        if f.endswith(".js") or f.endswith(".ts"):
            return "nodejs20"
    return "python312"


def get_functions_map(dagl_config):
    """Extract and normalize the functions mapping from dagl config.
    
    Returns:
      functions_map: dict of {workflow_name: function_name_string} (for backwards compat)
      functions_full: dict of {workflow_name: normalized_dict} (full platform info)
    """
    raw = dagl_config.get("functions", {})
    default_platform = dagl_config.get("platform", "aws")
    default_region = dagl_config.get("region", "eu-central-1")
    
    functions_map = {}  # Legacy format: {name: string}
    functions_full = {}  # Full format: {name: dict with platform info}
    
    for func_name, func_value in raw.items():
        entry = normalize_function_entry(func_value, default_platform, default_region)
        functions_map[func_name] = entry["name"]
        functions_full[func_name] = entry
    
    return functions_map, functions_full


def is_multi_cloud_workflow(functions_full):
    """Check if the workflow spans multiple cloud platforms."""
    platforms = set(entry["platform"] for entry in functions_full.values())
    return len(platforms) > 1


# ─── Compile Command ─────────────────────────────────────────────────────────────

def cmd_compile(args):
    """Compile workflow.dag into per-function orchestration configs.
    
    In Layer mode, this doesn't generate files — it outputs the configs
    that will be set as env vars during deploy.
    """
    from dagl_to_unum_ir import compile_dagl_to_unum_ir
    
    workflow_file = args.workflow or "workflow.dag"
    if not os.path.exists(workflow_file):
        print(f"\033[31mError:\033[0m {workflow_file} not found.")
        sys.exit(1)
    
    with open(workflow_file) as f:
        source = f.read()
    
    print(f"Compiling {workflow_file}...")
    
    # Compile DAGL source → configs + template
    configs, template = compile_dagl_to_unum_ir(source)
    
    # Load function mapping from dagl.yaml
    dagl_config = load_dagl_config(args.config or "dagl.yaml")
    functions_map, functions_full = get_functions_map(dagl_config)
    
    # Validate all referenced functions have mappings
    missing = []
    for func_name in configs:
        if func_name not in functions_map:
            missing.append(func_name)
    
    if missing:
        print(f"\033[31mError:\033[0m Functions not mapped in dagl.yaml: {', '.join(missing)}")
        print(f"Add them to the 'functions:' section:")
        for m in missing:
            print(f"  {m}: <lambda-function-name-or-arn>")
        sys.exit(1)
    
    # Resolve actual runtimes from deployed Lambda functions (AWS only)
    import boto3
    region = dagl_config.get("region", "eu-central-1")
    lambda_client = boto3.client("lambda", region_name=region)
    for func_name, func_ref in functions_map.items():
        if func_name in template.get("Functions", {}):
            entry = functions_full[func_name]
            if entry["platform"] != "aws":
                continue  # Skip non-AWS functions for runtime resolution
            try:
                info = lambda_client.get_function_configuration(FunctionName=func_ref)
                actual_runtime = info.get("Runtime", "python3.11")
                template["Functions"][func_name]["Properties"]["Runtime"] = actual_runtime
            except Exception:
                pass  # keep default if function not yet deployed

    # Print summary
    start_functions = [name for name, cfg in configs.items() if cfg.get('Start', False)]
    end_functions = [name for name, cfg in configs.items() if 'Next' not in cfg]
    
    print(f"\n\033[36mWorkflow Summary:\033[0m")
    print(f"  Name: {template.get('Globals', {}).get('ApplicationName', '?')}")
    print(f"  Functions: {len(configs)} ({', '.join(configs.keys())})")
    print(f"  Start: {', '.join(start_functions)}")
    print(f"  End: {', '.join(end_functions)}")
    
    api_config = template.get("Globals", {}).get("Api")
    if api_config:
        print(f"  API: {api_config.get('method', 'POST')} {api_config.get('path', '/')}")
    
    event_config = template.get("Globals", {}).get("Event")
    if event_config:
        print(f"  EventBridge: {event_config.get('source')} / {event_config.get('detailType', '*')}")
    
    # Registry validation (if configured)
    registry = _get_registry(dagl_config)
    if registry:
        print(f"\n\033[36mRegistry Check:\033[0m")
        issues = registry.validate_workflow(configs, functions_map)
        if not issues:
            print(f"  \033[32m✓\033[0m All functions registered, I/O schemas compatible")
        else:
            for level, msg in issues:
                if level == "error":
                    print(f"  \033[31m✗\033[0m {msg}")
                else:
                    print(f"  \033[33m!\033[0m {msg}")
            errors = [i for i in issues if i[0] == "error"]
            if errors:
                print(f"\n\033[31mRegistry validation failed.\033[0m Fix errors above or register functions with 'dagl registry register'.")
    
    print(f"\n\033[32mCompilation OK.\033[0m Run 'dagl deploy' to apply.")
    
    # Write compiled output for deploy to use
    compiled = {
        "configs": configs,
        "template": template,
        "functions_map": functions_map,
        "functions_full": functions_full,
    }
    with open(".dagl-compiled.json", "w") as f:
        json.dump(compiled, f, indent=2)
    
    return compiled


# ─── AWS Lambda Function URL Helper ──────────────────────────────────────────────

def _ensure_function_url(lambda_client, func_ref):
    """Ensure a Lambda Function URL is enabled. Returns the URL.
    
    Enables Function URL with AuthType=NONE for cross-platform invocation.
    If already enabled, returns the existing URL.
    """
    try:
        resp = lambda_client.get_function_url_config(FunctionName=func_ref)
        return resp["FunctionUrl"]
    except lambda_client.exceptions.ResourceNotFoundException:
        pass
    
    # Create Function URL
    resp = lambda_client.create_function_url_config(
        FunctionName=func_ref,
        AuthType='NONE',  # Public for simplicity; production should use AWS_IAM
        InvokeMode='BUFFERED',
    )
    url = resp["FunctionUrl"]
    
    # Add permission for public access
    try:
        lambda_client.add_permission(
            FunctionName=func_ref,
            StatementId='FunctionURLAllowPublicAccess',
            Action='lambda:InvokeFunctionUrl',
            Principal='*',
            FunctionUrlAuthType='NONE',
        )
    except lambda_client.exceptions.ResourceConflictException:
        pass  # Permission already exists
    
    return url


# ─── GCP Cloud Functions Deploy Helper ───────────────────────────────────────────

def _deploy_gcp_function(func_name, func_ref, func_config, entry,
                         function_map_json, ds_type, ds_name,
                         workflow_name, checkpoint, faas_platform):
    """Deploy DAGL orchestration to an existing GCP Cloud Function.
    
    Strategy:
    1. Create a temporary deploy directory with user source + DAGL runtime
    2. Use gcloud CLI to redeploy with DAGL entry point and env vars
    """
    import subprocess
    import shutil
    import tempfile
    
    gcp_project = entry.get("project", "")
    gcp_region = entry.get("region", "europe-west1")
    runtime = entry.get("runtime", "python312")
    
    # Original entry point (user's handler)
    original_handler = entry.get("handler", "main.handler")
    
    # DAGL entry point based on runtime family
    if "python" in runtime:
        dagl_entry_point = "gcp_http_handler"
    elif "node" in runtime:
        dagl_entry_point = "gcpHttpHandler"
    else:
        dagl_entry_point = "gcp_http_handler"
    
    # Find gcloud executable
    gcloud_cmd = _find_gcloud()
    
    # Build env vars for gcloud
    env_vars = {
        "DAGL_USER_HANDLER": original_handler,
        "DAGL_CONFIG": json.dumps(func_config),
        "DAGL_FUNCTION_MAP": function_map_json,
        "FAAS_PLATFORM": faas_platform,
        "FAAS_PLATFORM_NATIVE": "gcp",
        "UNUM_INTERMEDIARY_DATASTORE_TYPE": ds_type,
        "UNUM_INTERMEDIARY_DATASTORE_NAME": ds_name,
        "WORKFLOW_NAME": workflow_name,
        "CHECKPOINT": str(checkpoint).lower(),
        "GC": "false",
    }
    
    # If multi-cloud, pass AWS credentials so GCP can invoke AWS Lambda directly
    if faas_platform == "multi":
        import boto3.session
        session = boto3.session.Session()
        creds = session.get_credentials()
        if creds:
            frozen = creds.get_frozen_credentials()
            if frozen.access_key:
                env_vars["AWS_ACCESS_KEY_ID"] = frozen.access_key
            if frozen.secret_key:
                env_vars["AWS_SECRET_ACCESS_KEY"] = frozen.secret_key
            if frozen.token:
                env_vars["AWS_SESSION_TOKEN"] = frozen.token
        # Also pass default region
        aws_region = session.region_name or os.environ.get("AWS_DEFAULT_REGION", "eu-central-1")
        env_vars["AWS_DEFAULT_REGION"] = aws_region
    
    # Determine source directory
    source_dir = entry.get("source")
    
    # Create a temp deploy dir that bundles user source + DAGL runtime
    deploy_dir = tempfile.mkdtemp(prefix="dagl_gcp_")
    try:
        # Get user source: from local dir or download from existing GCP function
        if source_dir and os.path.isdir(source_dir):
            for item in os.listdir(source_dir):
                s = os.path.join(source_dir, item)
                d = os.path.join(deploy_dir, item)
                if os.path.isdir(s):
                    shutil.copytree(s, d)
                else:
                    shutil.copy2(s, d)
        else:
            # Download source from existing deployed GCP function
            _download_gcp_function_source(gcloud_cmd, func_ref, gcp_region, gcp_project, deploy_dir)
        
        # Bundle DAGL Python runtime into the deploy directory
        if "python" in runtime:
            _bundle_dagl_python_runtime(deploy_dir)
        elif "node" in runtime:
            _bundle_dagl_nodejs_runtime(deploy_dir)
        
        # Write env vars file for gcloud (YAML format)
        env_file = os.path.join(deploy_dir, ".env.yaml")
        with open(env_file, "w") as f:
            for k, v in env_vars.items():
                # Quote all values to avoid YAML parsing issues with JSON strings
                escaped = str(v).replace("'", "''")
                f.write(f"{k}: '{escaped}'\n")
        
        # Build gcloud command
        cmd = [
            gcloud_cmd, "functions", "deploy", func_ref,
            f"--region={gcp_region}",
            f"--entry-point={dagl_entry_point}",
            f"--env-vars-file={env_file}",
            f"--source={deploy_dir}",
            "--trigger-http",
            "--allow-unauthenticated",
            "--quiet",
        ]
        
        if gcp_project:
            cmd.append(f"--project={gcp_project}")
        
        if runtime:
            cmd.append(f"--runtime={runtime}")
        
        # Execute gcloud deploy
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        
        if result.returncode != 0:
            error_msg = result.stderr.strip() or result.stdout.strip()
            raise RuntimeError(f"gcloud: {error_msg}")
        
    finally:
        shutil.rmtree(deploy_dir, ignore_errors=True)
    
    return True


def _find_gcloud():
    """Find the gcloud CLI executable. Returns the full path."""
    import shutil as _shutil
    
    # Try PATH first
    gcloud = _shutil.which("gcloud")
    if gcloud:
        return gcloud
    
    # Common Windows install locations
    candidates = [
        os.path.join(os.environ.get("ProgramFiles(x86)", ""), "Google", "Cloud SDK", "google-cloud-sdk", "bin", "gcloud.cmd"),
        os.path.join(os.environ.get("ProgramFiles", ""), "Google", "Cloud SDK", "google-cloud-sdk", "bin", "gcloud.cmd"),
        os.path.join(os.environ.get("LOCALAPPDATA", ""), "Google", "Cloud SDK", "google-cloud-sdk", "bin", "gcloud.cmd"),
    ]
    
    for c in candidates:
        if c and os.path.isfile(c):
            return c
    
    raise FileNotFoundError(
        "gcloud CLI not found. Install it from https://cloud.google.com/sdk/docs/install "
        "or add it to PATH."
    )


def _download_gcp_function_source(gcloud_cmd, func_name, region, project, dest_dir):
    """Download the source of an existing GCP Cloud Function into dest_dir.
    
    Uses `gcloud functions describe` to get the source URL, then downloads and
    extracts it. This allows deploying DAGL orchestration to functions where the
    user doesn't have the source locally (e.g., deployed by another team).
    """
    import subprocess
    import zipfile
    import urllib.request
    
    # Get function details
    cmd = [gcloud_cmd, "functions", "describe", func_name,
           f"--region={region}", "--format=json"]
    if project:
        cmd.append(f"--project={project}")
    
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        raise RuntimeError(
            f"Cannot describe GCP function '{func_name}': {result.stderr.strip()}")
    
    import json as _json
    info = _json.loads(result.stdout)
    
    # Gen2 functions store source in buildConfig.source.storageSource
    build_config = info.get("buildConfig", {})
    source_info = build_config.get("source", {}).get("storageSource", {})
    bucket = source_info.get("bucket", "")
    obj = source_info.get("object", "")
    
    if not bucket or not obj:
        # Try gen1 format
        source_archive = info.get("sourceArchiveUrl", "")
        if source_archive:
            # Direct GCS URL: gs://bucket/object
            pass  # Will use gsutil below
        else:
            raise RuntimeError(
                f"Cannot determine source for GCP function '{func_name}'. "
                f"Specify 'source' in dagl.yaml to provide the local source directory.")
    
    # Download source zip using gsutil/gcloud storage
    zip_path = os.path.join(dest_dir, "_source.zip")
    
    if bucket and obj:
        gs_url = f"gs://{bucket}/{obj}"
    else:
        gs_url = source_archive
    
    dl_cmd = [gcloud_cmd, "storage", "cp", gs_url, zip_path, "--quiet"]
    result = subprocess.run(dl_cmd, capture_output=True, text=True, timeout=60)
    
    if result.returncode != 0:
        raise RuntimeError(
            f"Cannot download source for '{func_name}': {result.stderr.strip()}")
    
    # Extract zip into dest_dir
    with zipfile.ZipFile(zip_path, 'r') as zf:
        zf.extractall(dest_dir)
    
    os.remove(zip_path)


def _bundle_dagl_python_runtime(deploy_dir):
    """Copy DAGL Python runtime files into a GCP function deploy directory.
    
    Also creates a top-level main.py that imports gcp_http_handler from the
    DAGL runtime, so gcloud --entry-point=gcp_http_handler can find it.
    """
    import shutil as _shutil
    
    # Find the DAGL runtime source
    cli_dir = os.path.dirname(os.path.abspath(__file__))
    runtime_dir = os.path.join(cli_dir, "..", "layer", "python", "dagl_runtime")
    runtime_dir = os.path.normpath(runtime_dir)
    
    if not os.path.isdir(runtime_dir):
        raise FileNotFoundError(f"DAGL Python runtime not found at {runtime_dir}")
    
    # Copy dagl_runtime package into deploy dir (replace if already exists)
    dest = os.path.join(deploy_dir, "dagl_runtime")
    if os.path.isdir(dest):
        _shutil.rmtree(dest)
    _shutil.copytree(runtime_dir, dest, ignore=_shutil.ignore_patterns("__pycache__", "*.pyc"))
    
    # Create/update main.py with DAGL entry point import
    main_py = os.path.join(deploy_dir, "main.py")
    existing = ""
    if os.path.exists(main_py):
        with open(main_py) as f:
            existing = f.read()
    
    if "gcp_http_handler" not in existing:
        with open(main_py, "a") as f:
            f.write("\n# DAGL runtime entry point (injected by dagl deploy)\n")
            f.write("from dagl_runtime.main import gcp_http_handler\n")
    
    # Ensure requirements.txt includes dependencies
    req_file = os.path.join(deploy_dir, "requirements.txt")
    existing_reqs = ""
    if os.path.exists(req_file):
        with open(req_file) as f:
            existing_reqs = f.read()
    
    # Add functions-framework if not present
    if "functions-framework" not in existing_reqs:
        with open(req_file, "a") as f:
            f.write("\nfunctions-framework==3.*\n")
    
    # Add redis if not present (needed for multi-cloud datastore)
    if "redis" not in existing_reqs:
        with open(req_file, "a") as f:
            f.write("redis>=4.0\n")
    
    # Add boto3 if not present (needed for cross-platform Lambda invocation)
    if "boto3" not in existing_reqs:
        with open(req_file, "a") as f:
            f.write("boto3\n")


def _bundle_dagl_nodejs_runtime(deploy_dir):
    """Copy DAGL Node.js runtime files into a GCP function deploy directory."""
    import shutil as _shutil
    
    cli_dir = os.path.dirname(os.path.abspath(__file__))
    runtime_dir = os.path.join(cli_dir, "..", "layer", "nodejs", "node_modules", "dagl_runtime")
    runtime_dir = os.path.normpath(runtime_dir)
    
    if not os.path.isdir(runtime_dir):
        raise FileNotFoundError(f"DAGL Node.js runtime not found at {runtime_dir}")
    
    # Copy into node_modules/dagl_runtime (replace if already exists)
    dest = os.path.join(deploy_dir, "node_modules", "dagl_runtime")
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    if os.path.isdir(dest):
        _shutil.rmtree(dest)
    _shutil.copytree(runtime_dir, dest, ignore=_shutil.ignore_patterns("__pycache__", "*.pyc"))


def _undeploy_gcp_function(func_ref, entry):
    """Restore a GCP Cloud Function to its original entry point and env vars."""
    import subprocess
    
    gcloud_cmd = _find_gcloud()
    gcp_project = entry.get("project", "")
    gcp_region = entry.get("region", "europe-west1")
    original_handler = entry.get("handler", "handler")
    # Extract just the function name from module.function format
    original_entry = original_handler.rsplit(".", 1)[-1] if "." in original_handler else original_handler
    
    dagl_vars = ["DAGL_USER_HANDLER", "DAGL_CONFIG", "DAGL_FUNCTION_MAP",
                 "FAAS_PLATFORM", "FAAS_PLATFORM_NATIVE",
                 "UNUM_INTERMEDIARY_DATASTORE_TYPE",
                 "UNUM_INTERMEDIARY_DATASTORE_NAME", "WORKFLOW_NAME",
                 "CHECKPOINT", "GC"]
    
    cmd = [
        gcloud_cmd, "functions", "deploy", func_ref,
        f"--region={gcp_region}",
        f"--entry-point={original_entry}",
        f"--remove-env-vars={','.join(dagl_vars)}",
        "--trigger-http",
        "--allow-unauthenticated",
        "--quiet",
    ]
    
    source = entry.get("source")
    if source:
        cmd.append(f"--source={source}")
    
    if gcp_project:
        cmd.append(f"--project={gcp_project}")
    
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    
    if result.returncode != 0:
        error_msg = result.stderr.strip() or result.stdout.strip()
        raise RuntimeError(error_msg)


# ─── Deploy Command ──────────────────────────────────────────────────────────────

def cmd_deploy(args):
    """Deploy DAGL orchestration to existing functions (AWS Lambda + GCP Cloud Functions).
    
    For each function:
    1. Detect platform (aws/gcp from dagl.yaml)
    2. AWS: Attach DAGL runtime Layer + set handler/env vars
    3. GCP: Inject DAGL runtime files + set entry point/env vars via gcloud
    4. Enable Function URLs for cross-platform targets if multi-cloud
    5. Build enriched function map with platform + URL per function
    """
    import boto3
    
    # Load compiled output (or compile now)
    compiled_path = ".dagl-compiled.json"
    if not os.path.exists(compiled_path):
        print("No compiled output found. Compiling first...")
        compiled = cmd_compile(args)
    else:
        with open(compiled_path) as f:
            compiled = json.load(f)
    
    configs = compiled["configs"]
    template = compiled["template"]
    functions_map = compiled["functions_map"]
    
    dagl_config = load_dagl_config(args.config or "dagl.yaml")
    _, functions_full = get_functions_map(dagl_config)
    
    # If compiled didn't have functions_full, rebuild from dagl.yaml
    if "functions_full" in compiled:
        functions_full = compiled["functions_full"]
    
    region = dagl_config.get("region", "eu-central-1")
    explicit_layer_arn = args.layer_arn or dagl_config.get("layer_arn")
    checkpoint = dagl_config.get("checkpoint", True)
    workflow_name = template.get("Globals", {}).get("ApplicationName", "dagl-workflow")
    
    # Determine datastore config
    multi_cloud = is_multi_cloud_workflow(functions_full)
    datastore_cfg = dagl_config.get("datastore", {})
    
    if multi_cloud:
        # Multi-cloud workflows MUST use a shared datastore (Redis)
        ds_type = datastore_cfg.get("type", "redis")
        ds_name = datastore_cfg.get("url", dagl_config.get("datastore_name", DEFAULT_DS_NAME))
        if ds_type != "redis" and "url" not in datastore_cfg:
            print(f"\033[33mWarning:\033[0m Multi-cloud workflow detected. Consider using Redis as shared datastore.")
            print(f"  Add to dagl.yaml:\n    datastore:\n      type: redis\n      url: redis://your-redis-host:6379/0")
    else:
        ds_type = datastore_cfg.get("type", dagl_config.get("datastore_type", DEFAULT_DS_TYPE))
        ds_name = datastore_cfg.get("url", dagl_config.get("datastore_name", DEFAULT_DS_NAME))
    
    # AWS clients (may not be needed if all functions are GCP)
    aws_funcs = {k: v for k, v in functions_full.items() if v["platform"] == "aws"}
    gcp_funcs = {k: v for k, v in functions_full.items() if v["platform"] == "gcp"}
    
    lambda_client = None
    if aws_funcs:
        lambda_client = boto3.client("lambda", region_name=region)
    
    platforms_str = ", ".join(sorted(set(v["platform"] for v in functions_full.values())))
    
    # Display datastore info
    if ds_name.startswith("redis://") or ds_name.startswith("rediss://"):
        ds_display = ds_name
    else:
        ds_display = f"{ds_type}://{ds_name}"
    
    print(f"\n\033[36mDeploying DAGL orchestration:\033[0m {workflow_name}")
    print(f"  Platforms: {platforms_str}")
    print(f"  Functions: {len(configs)} ({len(aws_funcs)} AWS, {len(gcp_funcs)} GCP)")
    print(f"  Datastore: {ds_display}")
    if multi_cloud:
        print(f"  Mode: \033[33mmulti-cloud\033[0m (cross-platform HTTP invocation)")
    print()
    
    # ── Phase 1: Resolve functions to identifiers (ARNs, URLs) ──────────────
    
    # enriched_map: {func_name: {"platform": ..., "arn": ..., "url": ...}}
    enriched_map = {}
    
    # Resolve AWS functions
    for func_name in aws_funcs:
        func_ref = functions_map[func_name]
        entry = functions_full[func_name]
        
        if func_ref.startswith("arn:"):
            arn = func_ref
        else:
            try:
                resp = lambda_client.get_function(FunctionName=func_ref)
                arn = resp["Configuration"]["FunctionArn"]
            except lambda_client.exceptions.ResourceNotFoundException:
                print(f"  \033[31m✗\033[0m {func_name} → '{func_ref}' NOT FOUND (AWS)")
                sys.exit(1)
        
        enriched_map[func_name] = {
            "platform": "aws",
            "arn": arn,
            "region": entry.get("region", region),
        }
    
    # Resolve GCP functions (URL-based)
    for func_name in gcp_funcs:
        entry = functions_full[func_name]
        func_ref = functions_map[func_name]
        gcp_region = entry.get("region", "europe-west1")
        gcp_project = entry.get("project", "")
        
        # GCP function URL format: https://REGION-PROJECT.cloudfunctions.net/FUNCTION_NAME
        url = entry.get("url")
        if not url and gcp_project:
            url = f"https://{gcp_region}-{gcp_project}.cloudfunctions.net/{func_ref}"
        
        if not url:
            print(f"  \033[31m✗\033[0m {func_name}: GCP function requires 'url' or 'project' in dagl.yaml")
            sys.exit(1)
        
        enriched_map[func_name] = {
            "platform": "gcp",
            "url": url,
            "region": gcp_region,
            "project": gcp_project,
        }
    
    # ── Phase 2: Enable Function URLs for cross-platform invocation ─────────
    
    if multi_cloud and lambda_client:
        for func_name in aws_funcs:
            func_ref = functions_map[func_name]
            try:
                url = _ensure_function_url(lambda_client, func_ref)
                enriched_map[func_name]["url"] = url
                print(f"  \033[32m✓\033[0m {func_name}: Function URL enabled → {url[:60]}...")
            except Exception as e:
                print(f"  \033[33m!\033[0m {func_name}: Could not enable Function URL: {e}")
    
    # Build the function map JSON (new enriched format)
    function_map_json = json.dumps(enriched_map)
    
    # For single-cloud AWS workflows, also build legacy ARN map for backwards compat
    if not multi_cloud and not gcp_funcs:
        arn_map = {k: v["arn"] for k, v in enriched_map.items()}
        function_map_json = json.dumps(arn_map)
    
    # Determine FAAS_PLATFORM for env var
    faas_platform = "multi" if multi_cloud else "aws"
    
    # Initialize registry if configured
    registry = _get_registry(dagl_config)
    schemas = dagl_config.get("schemas", {})
    account_id = _get_account_id(region) if registry and aws_funcs else None
    
    # --strict: validate existing registry schemas before deploying
    if getattr(args, 'strict', False) and registry:
        issues = registry.validate_workflow(configs, functions_map)
        errors = [msg for level, msg in issues if level == "error"]
        if errors:
            print(f"\n\033[31m✗ --strict: Schema validation failed ({len(errors)} error(s)):\033[0m")
            for e in errors:
                print(f"    • {e}")
            print(f"\nDeploy aborted. Fix schemas or run without --strict.")
            sys.exit(1)
        warnings = [msg for level, msg in issues if level == "warning"]
        if warnings:
            for w in warnings:
                print(f"  \033[33m!\033[0m {w}")
    
    # Deploy each function
    for func_name, func_config in configs.items():
        func_ref = functions_map[func_name]
        entry = functions_full[func_name]
        platform = entry["platform"]
        
        if platform == "gcp":
            # ── GCP Cloud Functions deploy ──
            print(f"  Configuring {func_name} ({func_ref}) [GCP]...")
            try:
                _deploy_gcp_function(
                    func_name=func_name,
                    func_ref=func_ref,
                    func_config=func_config,
                    entry=entry,
                    function_map_json=function_map_json,
                    ds_type=ds_type,
                    ds_name=ds_name,
                    workflow_name=workflow_name,
                    checkpoint=checkpoint,
                    faas_platform=faas_platform,
                )
                print(f"    \033[32m✓\033[0m GCP function configured")
            except Exception as e:
                print(f"    \033[31m✗\033[0m GCP deploy failed: {e}")
                continue
        else:
            # ── AWS Lambda deploy ──
            print(f"  Configuring {func_name} ({func_ref}) [AWS]...")
            
            # Get current function configuration
            try:
                current = lambda_client.get_function_configuration(FunctionName=func_ref)
            except Exception as e:
                print(f"    \033[31m✗\033[0m Cannot read function: {e}")
                continue
            
            # Detect runtime and select appropriate layer + handler
            runtime = current.get("Runtime", "")
            runtime_family = detect_runtime_family(runtime)
            
            if explicit_layer_arn:
                layer_arn = explicit_layer_arn
            else:
                layer_name = dagl_config.get("layer_name", DEFAULT_LAYER_NAMES[runtime_family])
                layer_arn = resolve_latest_layer_arn(layer_name, region)
            
            dagl_handler = DAGL_HANDLERS[runtime_family]
            
            # Save original handler for restore (stored in env var)
            original_handler = current["Handler"]
            current_env = current.get("Environment", {}).get("Variables", {})
            
            # Don't overwrite if already configured by DAGL
            if "DAGL_USER_HANDLER" in current_env:
                original_handler = current_env["DAGL_USER_HANDLER"]
            
            # Build new environment
            new_env = dict(current_env)
            new_env.update({
                "DAGL_USER_HANDLER": original_handler,
                "DAGL_CONFIG": json.dumps(func_config),
                "DAGL_FUNCTION_MAP": function_map_json,
                "FAAS_PLATFORM": faas_platform,
                "FAAS_PLATFORM_NATIVE": "aws",
                "UNUM_INTERMEDIARY_DATASTORE_TYPE": ds_type,
                "UNUM_INTERMEDIARY_DATASTORE_NAME": ds_name,
                "WORKFLOW_NAME": workflow_name,
                "CHECKPOINT": str(checkpoint).lower(),
                "GC": "false",
            })
            
            # For Node.js: inject wrapper file into function code
            if runtime_family == "nodejs":
                try:
                    _inject_nodejs_wrapper(lambda_client, func_ref)
                    print(f"    \033[32m✓\033[0m Wrapper injected (dagl_wrapper.js)")
                except Exception as e:
                    print(f"    \033[31m✗\033[0m Failed to inject wrapper: {e}")
                    continue
            
            # Attach Layer (append to existing layers, avoid duplicates)
            current_layers = [l["Arn"] for l in current.get("Layers", [])]
            # Remove any existing dagl-runtime layer (python or nodejs)
            current_layers = [l for l in current_layers if "dagl-runtime-python" not in l and "dagl-runtime-nodejs" not in l]
            current_layers.append(layer_arn)
            
            # Update function configuration
            try:
                lambda_client.update_function_configuration(
                    FunctionName=func_ref,
                    Handler=dagl_handler,
                    Layers=current_layers,
                    Environment={"Variables": new_env},
                    Timeout=max(current.get("Timeout", 30), 60),  # Ensure at least 60s
                )
                print(f"    \033[32m✓\033[0m Handler: {original_handler} → {dagl_handler}")
                print(f"    \033[32m✓\033[0m Layer: {runtime_family} ({runtime}), config set")
            except Exception as e:
                print(f"    \033[31m✗\033[0m Failed: {e}")
                continue
        
        # Auto-register in registry
        if registry:
            try:
                func_schemas = schemas.get(func_name, {})
                in_schema = func_schemas.get("input")
                out_schema = func_schemas.get("output")
                
                # Auto-infer schemas from source code if not explicitly provided
                if not in_schema or not out_schema:
                    try:
                        from schema_inference import infer_schemas_from_lambda
                        inferred_in, inferred_out, _ = infer_schemas_from_lambda(lambda_client, func_ref)
                        if not in_schema and inferred_in:
                            in_schema = inferred_in
                        if not out_schema and inferred_out:
                            out_schema = inferred_out
                        src = []
                        if inferred_in: src.append("in")
                        if inferred_out: src.append("out")
                        if src:
                            print(f"    \033[32m✓\033[0m Schemas inferred from source ({'/'.join(src)})")
                    except Exception:
                        pass  # inference is best-effort
                
                func_arn = enriched_map[func_name].get("arn", enriched_map[func_name].get("url", ""))
                registry.register(
                    func_ref,
                    arn=func_arn,
                    runtime=runtime,
                    handler=original_handler,
                    region=region,
                    account_id=account_id,
                    platform=platform,
                    input_schema=in_schema,
                    output_schema=out_schema,
                )
                print(f"    \033[32m✓\033[0m Registered in registry")
            except Exception as e:
                print(f"    \033[33m!\033[0m Registry update failed: {e}")
    
    # ── API Gateway trigger ──────────────────────────────────────────────────
    api_config = template.get("Globals", {}).get("Api")
    if api_config:
        print(f"\n  Note: API Gateway ({api_config['method']} {api_config['path']}) requires manual setup")
        print(f"  or use 'dagl deploy --with-api' (coming soon)")
    
    # ── EventBridge trigger ──────────────────────────────────────────────────
    event_config = template.get("Globals", {}).get("Event")
    if event_config:
        # Build ARN map for EventBridge (AWS-only feature)
        eb_arn_map = {k: v.get("arn", "") for k, v in enriched_map.items() if v.get("arn")}
        _deploy_eventbridge(lambda_client, region, event_config, configs, eb_arn_map, workflow_name)
    
    print(f"\n\033[32mDeploy complete!\033[0m")
    print(f"  Invoke: dagl invoke -f input.json --wait")


def _deploy_eventbridge(lambda_client, region, event_config, configs, arn_map, workflow_name):
    """Create EventBridge rule targeting the start function."""
    import boto3
    
    events_client = boto3.client("events", region_name=region)
    
    # Find start function
    start_func = None
    for name, cfg in configs.items():
        if cfg.get("Start", False):
            start_func = name
            break
    
    if not start_func:
        return
    
    start_arn = arn_map[start_func]
    source = event_config.get("source", "custom")
    detail_type = event_config.get("detailType")
    rule_name = f"dagl-{workflow_name}-trigger"
    
    # Build event pattern
    pattern = {"source": [source]}
    if detail_type:
        pattern["detail-type"] = [detail_type]
    
    # Create/update EventBridge rule
    events_client.put_rule(
        Name=rule_name,
        EventPattern=json.dumps(pattern),
        State="ENABLED",
        Description=f"DAGL workflow trigger for {workflow_name}",
    )
    
    # Add target
    events_client.put_targets(
        Rule=rule_name,
        Targets=[{"Id": f"dagl-{start_func}", "Arn": start_arn}]
    )
    
    # Add permission for EventBridge to invoke the Lambda
    try:
        lambda_client.add_permission(
            FunctionName=start_arn,
            StatementId=f"dagl-eventbridge-{workflow_name}",
            Action="lambda:InvokeFunction",
            Principal="events.amazonaws.com",
            SourceArn=f"arn:aws:events:{region}:*:rule/{rule_name}",
        )
    except lambda_client.exceptions.ResourceConflictException:
        pass  # Permission already exists
    
    print(f"\n  \033[32m✓\033[0m EventBridge: {source} / {detail_type or '*'} → {start_func}")


# ─── Undeploy Command ────────────────────────────────────────────────────────────

def cmd_undeploy(args):
    """Remove DAGL orchestration — restore original function configs."""
    import boto3
    
    dagl_config = load_dagl_config(args.config or "dagl.yaml")
    region = dagl_config.get("region", "eu-central-1")
    functions_map, functions_full = get_functions_map(dagl_config)
    workflow_name = dagl_config.get("workflow_name", "dagl-workflow")
    
    lambda_client = boto3.client("lambda", region_name=region)
    
    print(f"\033[36mRemoving DAGL orchestration...\033[0m\n")
    
    for func_name, func_ref in functions_map.items():
        entry = functions_full[func_name]
        platform = entry["platform"]
        
        if platform == "gcp":
            print(f"  Restoring {func_name} ({func_ref}) [GCP]...")
            try:
                _undeploy_gcp_function(func_ref, entry)
                print(f"    \033[32m✓\033[0m GCP function restored")
            except Exception as e:
                print(f"    \033[33m!\033[0m GCP restore skipped: {e}")
            continue
        
        print(f"  Restoring {func_name} ({func_ref})...")
        
        try:
            current = lambda_client.get_function_configuration(FunctionName=func_ref)
        except Exception as e:
            print(f"    \033[31m✗\033[0m Cannot read function: {e}")
            continue
        
        current_env = current.get("Environment", {}).get("Variables", {})
        original_handler = current_env.get("DAGL_USER_HANDLER")
        
        if not original_handler:
            print(f"    Skipped (not managed by DAGL)")
            continue
        
        # Remove DAGL env vars
        dagl_vars = ["DAGL_USER_HANDLER", "DAGL_CONFIG", "DAGL_FUNCTION_MAP",
                     "FAAS_PLATFORM", "FAAS_PLATFORM_NATIVE",
                     "UNUM_INTERMEDIARY_DATASTORE_TYPE",
                     "UNUM_INTERMEDIARY_DATASTORE_NAME", "WORKFLOW_NAME",
                     "CHECKPOINT", "GC"]
        new_env = {k: v for k, v in current_env.items() if k not in dagl_vars}
        
        # Remove DAGL layer (python or nodejs)
        current_layers = [l["Arn"] for l in current.get("Layers", [])]
        new_layers = [l for l in current_layers if "dagl-runtime-python" not in l and "dagl-runtime-nodejs" not in l]
        
        lambda_client.update_function_configuration(
            FunctionName=func_ref,
            Handler=original_handler,
            Layers=new_layers,
            Environment={"Variables": new_env},
        )
        print(f"    \033[32m✓\033[0m Restored handler: {original_handler}")
        
        # Remove Node.js wrapper if present
        runtime = current.get("Runtime", "")
        if runtime.startswith("nodejs"):
            try:
                # Wait for config update to complete before modifying code
                waiter = lambda_client.get_waiter('function_updated_v2')
                waiter.wait(FunctionName=func_ref, WaiterConfig={'Delay': 2, 'MaxAttempts': 30})
                _remove_nodejs_wrapper(lambda_client, func_ref)
                print(f"    \033[32m✓\033[0m Wrapper removed (dagl_wrapper.js)")
            except Exception:
                pass  # Wrapper may not exist
    
    # Remove EventBridge rule
    try:
        events_client = boto3.client("events", region_name=region)
        rule_name = f"dagl-{workflow_name}-trigger"
        
        # Remove targets first
        events_client.remove_targets(Rule=rule_name, Ids=[f"dagl-{func_name}" for func_name in functions_map])
        events_client.delete_rule(Name=rule_name)
        print(f"\n  \033[32m✓\033[0m EventBridge rule removed")
    except Exception:
        pass
    
    print(f"\n\033[32mUndeploy complete.\033[0m Functions restored to original state.")


# ─── Invoke Command ──────────────────────────────────────────────────────────────

def cmd_invoke(args):
    """Invoke the workflow via the start function."""
    import boto3
    
    dagl_config = load_dagl_config(args.config or "dagl.yaml")
    region = dagl_config.get("region", "eu-central-1")
    functions_map_raw, functions_full = get_functions_map(dagl_config)
    
    # Datastore config for polling results
    datastore_cfg = dagl_config.get("datastore", {})
    multi_cloud = is_multi_cloud_workflow(functions_full)
    ds_type = datastore_cfg.get("type", dagl_config.get("datastore_type", DEFAULT_DS_TYPE))
    ds_name = datastore_cfg.get("url", dagl_config.get("datastore_name", DEFAULT_DS_NAME))
    
    # Load compiled to find start/end functions
    compiled_path = ".dagl-compiled.json"
    if not os.path.exists(compiled_path):
        print("\033[31mError:\033[0m Run 'dagl compile' first.")
        sys.exit(1)
    
    with open(compiled_path) as f:
        compiled = json.load(f)
    
    configs = compiled["configs"]
    functions_map = compiled["functions_map"]
    
    start_func = None
    end_functions = []
    for name, cfg in configs.items():
        if cfg.get("Start", False):
            start_func = name
        if "Next" not in cfg:
            end_functions.append(name)
    
    if not start_func:
        print("\033[31mError:\033[0m No start function found in workflow.")
        sys.exit(1)
    
    # Read input payload
    if args.file:
        with open(args.file) as f:
            payload = json.load(f)
    else:
        payload = {}
    
    session_id = str(uuid.uuid4())
    
    # Wrap in DAGL envelope
    dagl_event = {
        "Data": {"Source": "http", "Value": payload},
        "Session": session_id,
    }
    
    func_ref = functions_map[start_func]
    start_entry = functions_full[start_func]
    start_platform = start_entry["platform"]
    
    print(f"\033[36mWorkflow:\033[0m {compiled['template']['Globals']['ApplicationName']}")
    print(f"  Start: {start_func} ({func_ref}) [{start_platform}]")
    print(f"  End: {', '.join(end_functions)}")
    print(f"  Session: {session_id}")
    
    # Invoke start function based on platform
    if start_platform == "gcp":
        # GCP: HTTP POST to function URL
        url = start_entry.get("url")
        if not url:
            gcp_project = start_entry.get("project", "")
            gcp_region = start_entry.get("region", "europe-west1")
            url = f"https://{gcp_region}-{gcp_project}.cloudfunctions.net/{func_ref}"
        
        import urllib.request
        req = urllib.request.Request(
            url,
            data=json.dumps(dagl_event).encode('utf-8'),
            headers={'Content-Type': 'application/json'},
            method='POST'
        )
        try:
            with urllib.request.urlopen(req, timeout=10) as resp:
                status = resp.status
                resp.read()
            print(f"  Invoked (HTTP): {status}")
        except Exception as e:
            print(f"  \033[31m✗\033[0m Failed to invoke: {e}")
            sys.exit(1)
    else:
        # AWS: Lambda async invoke
        lambda_client = boto3.client("lambda", region_name=region)
        response = lambda_client.invoke(
            FunctionName=func_ref,
            InvocationType="Event",
            Payload=json.dumps(dagl_event),
        )
        print(f"  Invoked: {response['StatusCode']}")
    
    if not args.wait:
        print(f"\n  Fire-and-forget. Check datastore for results: {session_id}")
        return
    
    # Poll for completion based on datastore type
    timeout = args.timeout or 30
    print(f"  Waiting for completion (timeout: {timeout}s)...", end="", flush=True)
    
    start_time = time.time()
    result = None
    
    if ds_type == "redis":
        # Poll Redis for end function checkpoint
        import redis
        r = redis.Redis.from_url(ds_name, decode_responses=True)
        
        while time.time() - start_time < timeout:
            time.sleep(1)
            print(".", end="", flush=True)
            
            for end_func in end_functions:
                key = f"dagl:ckpt:{session_id}/{end_func}-output"
                raw = r.get(key)
                if raw:
                    data = json.loads(raw)
                    if isinstance(data, dict) and "User" in data:
                        result = json.loads(data["User"]) if isinstance(data["User"], str) else data["User"]
                    else:
                        result = data
                    break
            
            if result is not None:
                break
    else:
        # Poll DynamoDB
        dynamodb = boto3.resource("dynamodb", region_name=region)
        table = dynamodb.Table(ds_name)
        
        while time.time() - start_time < timeout:
            time.sleep(1)
            print(".", end="", flush=True)
            
            for end_func in end_functions:
                key = f"{session_id}/{end_func}-output"
                try:
                    resp = table.get_item(Key={"Name": key})
                    if "Item" in resp:
                        item = resp["Item"]
                        result = json.loads(item.get("User", "null"))
                        break
                except Exception:
                    continue
            
            if result is not None:
                break
    
    elapsed = time.time() - start_time
    
    if result is not None:
        print(f"\n\n\033[32mCompleted in ~{int(elapsed)}s\033[0m\n")
        print(json.dumps(result, indent=2))
    else:
        print(f"\n\n\033[33mTimeout after {timeout}s.\033[0m Check datastore: {session_id}")


# ─── Status Command ──────────────────────────────────────────────────────────────

def cmd_status(args):
    """Show current DAGL orchestration state for mapped functions."""
    import boto3
    
    dagl_config = load_dagl_config(args.config or "dagl.yaml")
    region = dagl_config.get("region", "eu-central-1")
    functions_map = dagl_config.get("functions", {})
    
    lambda_client = boto3.client("lambda", region_name=region)
    
    print(f"\033[36mDAGL Status:\033[0m\n")
    
    for func_name, func_ref in functions_map.items():
        try:
            current = lambda_client.get_function_configuration(FunctionName=func_ref)
            env = current.get("Environment", {}).get("Variables", {})
            handler = current["Handler"]
            runtime = current["Runtime"]
            layers = [l["Arn"].split(":")[-2] for l in current.get("Layers", [])]
            
            is_dagl = "DAGL_USER_HANDLER" in env
            status = "\033[32m● DAGL\033[0m" if is_dagl else "\033[90m○ standalone\033[0m"
            
            print(f"  {status} {func_name} ({func_ref})")
            print(f"         Runtime: {runtime}, Handler: {handler}")
            if layers:
                print(f"         Layers: {', '.join(layers)}")
            if is_dagl:
                print(f"         Original: {env['DAGL_USER_HANDLER']}")
            print()
        except Exception as e:
            print(f"  \033[31m✗\033[0m {func_name} ({func_ref}): {e}\n")


# ─── Init Command ────────────────────────────────────────────────────────────────

def cmd_init(args):
    """Initialize a new DAGL workflow project."""
    
    name = args.name or "my-workflow"
    
    # Create dagl.yaml
    if os.path.exists("dagl.yaml"):
        print("dagl.yaml already exists. Skipping.")
    else:
        config = f"""# DAGL Workflow Configuration
platform: aws
region: eu-central-1

# Map workflow function names to deployed Lambda function names/ARNs
functions:
  # FunctionA: my-project-function-a
  # FunctionB: arn:aws:lambda:eu-central-1:123456789:function:my-func

# Optional settings
# checkpoint: true
# datastore_name: unum-intermediate-datastore
# datastore_type: dynamodb
# layer_arn: arn:aws:lambda:eu-central-1:683003725669:layer:dagl-runtime-python:1
"""
        with open("dagl.yaml", "w") as f:
            f.write(config)
        print(f"  \033[32m✓\033[0m dagl.yaml")
    
    # Create workflow.dag
    if os.path.exists("workflow.dag"):
        print("workflow.dag already exists. Skipping.")
    else:
        workflow = f"""@workflow("{name}")
@checkpoint(true)

let result = FunctionA(input)
return FunctionB(result)
"""
        with open("workflow.dag", "w") as f:
            f.write(workflow)
        print(f"  \033[32m✓\033[0m workflow.dag")
    
    print(f"\n  Next steps:")
    print(f"    1. Edit dagl.yaml — map function names to your Lambda functions")
    print(f"    2. Edit workflow.dag — define the data flow")
    print(f"    3. dagl compile")
    print(f"    4. dagl deploy")


# ─── Registry Commands ───────────────────────────────────────────────────────────

def cmd_registry(args):
    """Manage the function registry."""
    sub = args.registry_command

    if sub == "configure":
        _registry_configure(args)
    elif sub == "list":
        _registry_list(args)
    elif sub == "check":
        _registry_check(args)
    elif sub == "register":
        _registry_register(args)
    elif sub == "schema":
        _registry_schema(args)
    else:
        print("Usage: dagl registry {configure|list|check|register|schema}")


def _registry_configure(args):
    """Add or update registry config in dagl.yaml."""
    import yaml

    config_path = args.config or "dagl.yaml"
    url = args.url or f"redis://{args.host or 'localhost'}:{args.port or 6379}/{args.db or 0}"

    # Test connection first
    try:
        from registry import Registry
        reg = Registry(url=url)
        print(f"\033[32m✓\033[0m Connected to Redis: {url}")
    except ImportError:
        print("\033[31mError:\033[0m redis package not installed. Run: pip install redis")
        sys.exit(1)
    except Exception as e:
        print(f"\033[31mError:\033[0m Cannot connect to {url}: {e}")
        sys.exit(1)

    # Update dagl.yaml
    if os.path.exists(config_path):
        with open(config_path) as f:
            config = yaml.safe_load(f) or {}
    else:
        config = {}

    config["registry"] = {"url": url}

    with open(config_path, "w") as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)

    print(f"\033[32m✓\033[0m Registry configured in {config_path}")


def _registry_list(args):
    """List all functions in the registry."""
    dagl_config = load_dagl_config(args.config or "dagl.yaml")
    registry = _get_registry(dagl_config)
    if not registry:
        print("\033[31mError:\033[0m Registry not configured. Run: dagl registry configure --url redis://...")
        sys.exit(1)

    account_filter = args.account if hasattr(args, 'account') and args.account else None
    names = registry.list_functions(account_id=account_filter)

    if not names:
        print("No functions registered.")
        return

    print(f"\033[36mRegistered Functions:\033[0m ({len(names)})\n")
    for name in names:
        info = registry.lookup(name)
        if not info:
            continue
        runtime = info.get("runtime", "?")
        region = info.get("region", "?")
        deployed = info.get("deployed_at", "?")
        has_input = "input_schema" in info
        has_output = "output_schema" in info
        schema_indicator = ""
        if has_input or has_output:
            parts = []
            if has_input:
                parts.append("in")
            if has_output:
                parts.append("out")
            schema_indicator = f" [{'/'.join(parts)}]"

        print(f"  \033[32m●\033[0m {name}")
        print(f"    {runtime} | {region} | deployed {deployed}{schema_indicator}")
        if has_input:
            print(f"    Input:  {info['input_schema']}")
        if has_output:
            print(f"    Output: {info['output_schema']}")
        print()


def _registry_check(args):
    """Check if all workflow functions are registered and I/O schemas match."""
    dagl_config = load_dagl_config(args.config or "dagl.yaml")
    registry = _get_registry(dagl_config)
    if not registry:
        print("\033[31mError:\033[0m Registry not configured. Run: dagl registry configure --url redis://...")
        sys.exit(1)

    # Load compiled workflow (or compile on the fly)
    compiled_path = ".dagl-compiled.json"
    if not os.path.exists(compiled_path):
        print("No compiled workflow found. Run 'dagl compile' first.")
        sys.exit(1)

    with open(compiled_path) as f:
        compiled = json.load(f)

    configs = compiled["configs"]
    functions_map = compiled["functions_map"]

    print(f"\033[36mRegistry Validation:\033[0m\n")

    # 1. Check all functions exist
    all_ok = True
    for func_name, func_ref in functions_map.items():
        if registry.check_deployed(func_ref):
            info = registry.lookup(func_ref)
            print(f"  \033[32m✓\033[0m {func_name} → {func_ref} ({info.get('runtime', '?')})")
        else:
            print(f"  \033[31m✗\033[0m {func_name} → {func_ref} (NOT REGISTERED)")
            all_ok = False

    # 2. Validate I/O schemas
    print()
    issues = registry.validate_workflow(configs, functions_map)
    if not issues:
        print(f"  \033[32m✓\033[0m All I/O schemas compatible")
    else:
        for level, msg in issues:
            if level == "error":
                print(f"  \033[31m✗\033[0m {msg}")
                all_ok = False
            else:
                print(f"  \033[33m!\033[0m {msg}")

    if all_ok:
        print(f"\n\033[32mAll checks passed.\033[0m")
    else:
        print(f"\n\033[31mValidation failed.\033[0m")
        sys.exit(1)


def _registry_register(args):
    """Register an individual Lambda function in the registry."""
    import boto3

    dagl_config = load_dagl_config(args.config or "dagl.yaml")
    registry = _get_registry(dagl_config)
    if not registry:
        print("\033[31mError:\033[0m Registry not configured. Run: dagl registry configure --url redis://...")
        sys.exit(1)

    func_name = args.function
    region = dagl_config.get("region", "eu-central-1")
    lambda_client = boto3.client("lambda", region_name=region)

    try:
        info = lambda_client.get_function_configuration(FunctionName=func_name)
    except Exception as e:
        print(f"\033[31mError:\033[0m Cannot read function '{func_name}': {e}")
        sys.exit(1)

    account_id = _get_account_id(region)
    arn = info["FunctionArn"]
    runtime = info.get("Runtime", "unknown")
    handler = info["Handler"]

    # Parse optional schemas from --input / --output
    input_schema = json.loads(args.input_schema) if args.input_schema else None
    output_schema = json.loads(args.output_schema) if args.output_schema else None

    # Auto-infer schemas from source code if not explicitly provided
    inferred = False
    if not input_schema or not output_schema:
        try:
            from schema_inference import infer_schemas_from_lambda
            inferred_in, inferred_out, _ = infer_schemas_from_lambda(lambda_client, func_name)
            if not input_schema and inferred_in:
                input_schema = inferred_in
                inferred = True
            if not output_schema and inferred_out:
                output_schema = inferred_out
                inferred = True
        except Exception as e:
            print(f"  \033[33m!\033[0m Schema inference failed: {e}")

    registry.register(
        func_name,
        arn=arn,
        runtime=runtime,
        handler=handler,
        region=region,
        account_id=account_id,
        input_schema=input_schema,
        output_schema=output_schema,
    )

    print(f"\033[32m✓\033[0m Registered: {func_name}")
    print(f"  ARN: {arn}")
    print(f"  Runtime: {runtime}")
    if input_schema:
        source_tag = " (inferred)" if inferred else ""
        print(f"  Input:  {input_schema}{source_tag}")
    if output_schema:
        source_tag = " (inferred)" if inferred else ""
        print(f"  Output: {output_schema}{source_tag}")


def _registry_schema(args):
    """Set input/output schemas for a registered function."""
    dagl_config = load_dagl_config(args.config or "dagl.yaml")
    registry = _get_registry(dagl_config)
    if not registry:
        print("\033[31mError:\033[0m Registry not configured.")
        sys.exit(1)

    func_name = args.function

    if not registry.check_deployed(func_name):
        print(f"\033[31mError:\033[0m '{func_name}' is not registered. Register it first with: dagl registry register {func_name}")
        sys.exit(1)

    input_schema = json.loads(args.input_schema) if args.input_schema else None
    output_schema = json.loads(args.output_schema) if args.output_schema else None

    if not input_schema and not output_schema:
        # Show current schemas
        info = registry.lookup(func_name)
        print(f"\033[36mSchemas for {func_name}:\033[0m")
        if "input_schema" in info:
            print(f"  Input:  {json.dumps(info['input_schema'])}")
        else:
            print(f"  Input:  (not set)")
        if "output_schema" in info:
            print(f"  Output: {json.dumps(info['output_schema'])}")
        else:
            print(f"  Output: (not set)")
        return

    registry.set_schema(func_name, input_schema=input_schema, output_schema=output_schema)
    print(f"\033[32m✓\033[0m Schemas updated for {func_name}")
    if input_schema:
        print(f"  Input:  {json.dumps(input_schema)}")
    if output_schema:
        print(f"  Output: {json.dumps(output_schema)}")


# ─── Main ────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        prog="dagl",
        description="DAGL — Serverless workflow orchestration via direct Lambda invocation"
    )
    parser.add_argument("--config", "-c", default="dagl.yaml", help="Path to dagl.yaml")
    
    subparsers = parser.add_subparsers(dest="command")
    
    # init
    p_init = subparsers.add_parser("init", help="Initialize a DAGL workflow project")
    p_init.add_argument("name", nargs="?", help="Workflow name")
    
    # compile
    p_compile = subparsers.add_parser("compile", help="Compile workflow.dag")
    p_compile.add_argument("--workflow", "-w", help="Workflow file (default: workflow.dag)")
    
    # deploy
    p_deploy = subparsers.add_parser("deploy", help="Deploy orchestration to functions")
    p_deploy.add_argument("--workflow", "-w", help="Workflow file (default: workflow.dag)")
    p_deploy.add_argument("--layer-arn", help="Override DAGL runtime Layer ARN")
    p_deploy.add_argument("--strict", action="store_true", help="Abort deploy if registry schema validation fails")
    
    # undeploy
    p_undeploy = subparsers.add_parser("undeploy", help="Remove orchestration, restore functions")
    
    # invoke
    p_invoke = subparsers.add_parser("invoke", help="Invoke the workflow")
    p_invoke.add_argument("-f", "--file", help="Input JSON file")
    p_invoke.add_argument("--wait", action="store_true", help="Wait for result")
    p_invoke.add_argument("--timeout", type=int, default=30, help="Wait timeout (seconds)")
    
    # status
    p_status = subparsers.add_parser("status", help="Show orchestration status")
    
    # registry
    p_registry = subparsers.add_parser("registry", help="Manage function registry")
    reg_sub = p_registry.add_subparsers(dest="registry_command")
    
    p_reg_configure = reg_sub.add_parser("configure", help="Configure Redis connection")
    p_reg_configure.add_argument("--url", help="Redis URL (e.g., redis://localhost:6379/0)")
    p_reg_configure.add_argument("--host", help="Redis host (default: localhost)")
    p_reg_configure.add_argument("--port", type=int, help="Redis port (default: 6379)")
    p_reg_configure.add_argument("--db", type=int, help="Redis DB (default: 0)")
    
    p_reg_list = reg_sub.add_parser("list", help="List registered functions")
    p_reg_list.add_argument("--account", help="Filter by AWS account ID")
    
    p_reg_check = reg_sub.add_parser("check", help="Validate workflow against registry")
    
    p_reg_register = reg_sub.add_parser("register", help="Register a Lambda function")
    p_reg_register.add_argument("function", help="Lambda function name or ARN")
    p_reg_register.add_argument("--input-schema", dest="input_schema", help='Input schema JSON (e.g., \'{"text": "string"}\')')
    p_reg_register.add_argument("--output-schema", dest="output_schema", help='Output schema JSON (e.g., \'{"tokens": "string[]"}\')')
    
    p_reg_schema = reg_sub.add_parser("schema", help="Set or view schemas for a function")
    p_reg_schema.add_argument("function", help="Function name")
    p_reg_schema.add_argument("--input-schema", dest="input_schema", help="Input schema JSON")
    p_reg_schema.add_argument("--output-schema", dest="output_schema", help="Output schema JSON")
    
    args = parser.parse_args()
    
    if args.command == "init":
        cmd_init(args)
    elif args.command == "compile":
        cmd_compile(args)
    elif args.command == "deploy":
        cmd_deploy(args)
    elif args.command == "undeploy":
        cmd_undeploy(args)
    elif args.command == "invoke":
        cmd_invoke(args)
    elif args.command == "status":
        cmd_status(args)
    elif args.command == "registry":
        cmd_registry(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
