AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Function:
    Environment:
      Variables:
        CHECKPOINT: true
        EAGER: false
        FAAS_PLATFORM: aws
        GC: false
        UNUM_INTERMEDIARY_DATASTORE_NAME: unum-intermediate-datastore
        UNUM_INTERMEDIARY_DATASTORE_TYPE: dynamodb
    Timeout: 900
Outputs:
  HelloFunction:
    Value: !GetAtt HelloFunction.Arn
  WorldFunction:
    Value: !GetAtt WorldFunction.Arn
Resources:
  HelloFunction:
    Properties:
      CodeUri: hello/
      Handler: main.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Runtime: python3.11
    Type: AWS::Serverless::Function
  WorldFunction:
    Properties:
      CodeUri: world/
      Handler: main.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
        - AmazonS3FullAccess
        - AmazonSNSFullAccess
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
      Runtime: python3.11
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
