AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Environment:
      Variables:
        CHECKPOINT: true
        EAGER: false
        FAAS_PLATFORM: aws
        GC: false
        UNUM_INTERMEDIARY_DATASTORE_NAME: unum-streaming-demo
        UNUM_INTERMEDIARY_DATASTORE_TYPE: dynamodb
    Timeout: 600
    MemorySize: 256
Resources:
  GeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Generator/
      Handler: main.lambda_handler
      Runtime: python3.11
      Policies:
        - AWSLambdaRole
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AWSLambdaBasicExecutionRole
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Processor/
      Handler: main.lambda_handler
      Runtime: python3.11
      Policies:
        - AWSLambdaRole
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AWSLambdaBasicExecutionRole
  AnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Analyzer/
      Handler: main.lambda_handler
      Runtime: python3.11
      Policies:
        - AWSLambdaRole
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AWSLambdaBasicExecutionRole
  ReporterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Reporter/
      Handler: main.lambda_handler
      Runtime: python3.11
      Policies:
        - AWSLambdaRole
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AWSLambdaBasicExecutionRole
Outputs:
  GeneratorFunction:
    Value: !GetAtt GeneratorFunction.Arn
  ProcessorFunction:
    Value: !GetAtt ProcessorFunction.Arn
  AnalyzerFunction:
    Value: !GetAtt AnalyzerFunction.Arn
  ReporterFunction:
    Value: !GetAtt ReporterFunction.Arn
