AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Function:
    Environment:
      Variables:
        CHECKPOINT: true
        EAGER: true
        FAAS_PLATFORM: aws
        GC: false
        UNUM_INTERMEDIARY_DATASTORE_NAME: unum-intermediate-datastore-iot
        UNUM_INTERMEDIARY_DATASTORE_TYPE: dynamodb
    Timeout: 900
Outputs:
  ActionDispatcherFunction:
    Value: !GetAtt ActionDispatcherFunction.Arn
  FailureModelFunction:
    Value: !GetAtt FailureModelFunction.Arn
  MachineStateShiftCheckFunction:
    Value: !GetAtt MachineStateShiftCheckFunction.Arn
  SafetyCheckFunction:
    Value: !GetAtt SafetyCheckFunction.Arn
  SensorIngestFunction:
    Value: !GetAtt SensorIngestFunction.Arn
  WindowingComputeFFTFunction:
    Value: !GetAtt WindowingComputeFFTFunction.Arn
Resources:
  ActionDispatcherFunction:
    Properties:
      CodeUri: action-dispatcher/
      Environment:
        Variables:
          UNUM_FUTURE_BASED: 'true'
      Handler: main.lambda_handler
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
        - AWSLambdaRole
        - AWSLambdaBasicExecutionRole
      Runtime: python3.11
    Type: AWS::Serverless::Function
  FailureModelFunction:
    Properties:
      CodeUri: fused_build/FailureModel/
      Handler: main.lambda_handler
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
        - AWSLambdaRole
        - AWSLambdaBasicExecutionRole
      Runtime: python3.11
    Type: AWS::Serverless::Function
  MachineStateShiftCheckFunction:
    Properties:
      CodeUri: fused_build/MachineStateShiftCheck/
      Handler: main.lambda_handler
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
        - AWSLambdaRole
        - AWSLambdaBasicExecutionRole
      Runtime: python3.11
    Type: AWS::Serverless::Function
  SafetyCheckFunction:
    Properties:
      CodeUri: fused_build/SafetyCheck/
      Handler: main.lambda_handler
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
        - AWSLambdaRole
        - AWSLambdaBasicExecutionRole
      Runtime: python3.11
    Type: AWS::Serverless::Function
  SensorIngestFunction:
    Properties:
      CodeUri: fused_build/SensorIngest/
      Handler: main.lambda_handler
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
        - AWSLambdaRole
        - AWSLambdaBasicExecutionRole
      Runtime: python3.11
    Type: AWS::Serverless::Function
  WindowingComputeFFTFunction:
    Properties:
      CodeUri: fused_build/WindowingComputeFFT/
      Handler: main.lambda_handler
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
        - AWSLambdaRole
        - AWSLambdaBasicExecutionRole
      Runtime: python3.11
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
