AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Streaming Benchmark - Partial Parameter Streaming vs Normal Execution

Globals:
  Function:
    Timeout: 300
    MemorySize: 256
    Runtime: python3.11

Resources:
  # DynamoDB table for unum intermediary data store
  UnumDataStore:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-datastore
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Name
          AttributeType: S
      KeySchema:
        - AttributeName: Name
          KeyType: HASH

  # Producer function - computes 3 fields sequentially
  Producer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-Producer
      CodeUri: Producer/
      Handler: main.lambda_handler
      Environment:
        Variables:
          FAAS_PLATFORM: aws
          UNUM_INTERMEDIARY_DATASTORE_TYPE: dynamodb
          UNUM_INTERMEDIARY_DATASTORE_NAME: !Ref UnumDataStore
          GC: "False"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UnumDataStore
        - LambdaInvokePolicy:
            FunctionName: !Sub ${AWS::StackName}-Consumer

  # Consumer function - receives fields (some as futures)
  Consumer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-Consumer
      CodeUri: Consumer/
      Handler: main.lambda_handler
      Environment:
        Variables:
          FAAS_PLATFORM: aws
          UNUM_INTERMEDIARY_DATASTORE_TYPE: dynamodb
          UNUM_INTERMEDIARY_DATASTORE_NAME: !Ref UnumDataStore
          GC: "False"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UnumDataStore
        - LambdaInvokePolicy:
            FunctionName: !Sub ${AWS::StackName}-Aggregator

  # Aggregator function - final result
  Aggregator:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-Aggregator
      CodeUri: Aggregator/
      Handler: main.lambda_handler
      Environment:
        Variables:
          FAAS_PLATFORM: aws
          UNUM_INTERMEDIARY_DATASTORE_TYPE: dynamodb
          UNUM_INTERMEDIARY_DATASTORE_NAME: !Ref UnumDataStore
          GC: "False"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UnumDataStore

Outputs:
  ProducerArn:
    Value: !GetAtt Producer.Arn
  ConsumerArn:
    Value: !GetAtt Consumer.Arn
  AggregatorArn:
    Value: !GetAtt Aggregator.Arn
  DataStoreTable:
    Value: !Ref UnumDataStore
