AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Function:
    Environment:
      Variables:
        CHECKPOINT: true
        FAAS_PLATFORM: aws
        GC: false
        UNUM_INTERMEDIARY_DATASTORE_NAME: unum-intermediate-datastore
        UNUM_INTERMEDIARY_DATASTORE_TYPE: dynamodb
    Timeout: 900
Outputs:
  ByeFunction:
    Value: !GetAtt ByeFunction.Arn
  HelloFunction:
    Value: !GetAtt HelloFunction.Arn
  StartFunction:
    Value: !GetAtt StartFunction.Arn
  WorldFunction:
    Value: !GetAtt WorldFunction.Arn
Resources:
  ByeFunction:
    Properties:
      CodeUri: bye/
      Handler: main.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaRole
        - AmazonS3FullAccess
        - AWSLambdaBasicExecutionRole
      Runtime: python3.13
    Type: AWS::Serverless::Function
  HelloFunction:
    Properties:
      CodeUri: hello/
      Handler: main.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaRole
        - AmazonS3FullAccess
        - AWSLambdaBasicExecutionRole
      Runtime: python3.13
    Type: AWS::Serverless::Function
  StartFunction:
    Properties:
      CodeUri: start/
      Handler: main.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaRole
        - AmazonS3FullAccess
        - AWSLambdaBasicExecutionRole
      Runtime: python3.13
    Type: AWS::Serverless::Function
  WorldFunction:
    Properties:
      CodeUri: world/
      Handler: main.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaRole
        - AmazonS3FullAccess
        - AWSLambdaBasicExecutionRole
      Runtime: python3.13
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
